blank_issues_enabled: false
contact_links:
  - name: Questions & ideas
    url: https://github.com/lodeflow/LodeFlow/discussions
    about: Not sure it's a bug? Open-ended idea? Start a discussion instead.
